package mend

import (
	"strings"
	"testing"

	"alive.name/internal/domain"
)

// Unit tests: pure logic only. GenerateMailmap produces text with no I/O.
// WriteMailmapFile touches the filesystem and is tested under the integration tag.

func TestGenerateMailmap(testingHandle *testing.T) {
	testCases := []struct {
		caseName            string
		category            string
		oldIdentity         domain.OldIdentity
		newIdentity         domain.NewIdentity
		expectError         bool
		expectedSubstrings  []string
		forbiddenSubstrings []string
	}{
		{
			caseName:    "names and emails produce full mappings",
			category:    "happy",
			oldIdentity: domain.OldIdentity{Names: []string{"Old Name"}, Emails: []string{"old@example.test"}},
			newIdentity: domain.NewIdentity{Name: "New Name", Email: "new@example.test"},
			expectedSubstrings: []string{
				"New Name <new@example.test> <old@example.test>",
				"New Name <new@example.test> Old Name <new@example.test>",
				"New Name <new@example.test> Old Name <old@example.test>",
				"# Generated by alive.name",
			},
		},
		{
			caseName:           "names only still produce valid entries",
			category:           "negative",
			oldIdentity:        domain.OldIdentity{Names: []string{"Old Name"}},
			newIdentity:        domain.NewIdentity{Name: "New Name", Email: "new@example.test"},
			expectedSubstrings: []string{"New Name <new@example.test> Old Name <new@example.test>"},
		},
		{
			caseName:           "unicode names are handled",
			category:           "edge",
			oldIdentity:        domain.OldIdentity{Names: []string{"Óld Támé"}, Emails: []string{"old@example.test"}},
			newIdentity:        domain.NewIdentity{Name: "Nëw Nâmé", Email: "new@example.test"},
			expectedSubstrings: []string{"Nëw Nâmé <new@example.test> Óld Támé <old@example.test>"},
		},
		{
			caseName:           "identity needing no change still produces a valid line",
			category:           "edge",
			oldIdentity:        domain.OldIdentity{Names: []string{"New Name"}, Emails: []string{"new@example.test"}},
			newIdentity:        domain.NewIdentity{Name: "New Name", Email: "new@example.test"},
			expectedSubstrings: []string{"New Name <new@example.test> <new@example.test>"},
		},
		{
			caseName:    "empty new name is an error",
			category:    "error",
			oldIdentity: domain.OldIdentity{Names: []string{"Old Name"}},
			newIdentity: domain.NewIdentity{Name: "  ", Email: "new@example.test"},
			expectError: true,
		},
		{
			caseName:    "empty new email is an error",
			category:    "error",
			oldIdentity: domain.OldIdentity{Names: []string{"Old Name"}},
			newIdentity: domain.NewIdentity{Name: "New Name", Email: ""},
			expectError: true,
		},
		{
			caseName:    "no old identity is an error",
			category:    "error",
			oldIdentity: domain.OldIdentity{},
			newIdentity: domain.NewIdentity{Name: "New Name", Email: "new@example.test"},
			expectError: true,
		},
	}
	for _, testCase := range testCases {
		testingHandle.Run(testCase.caseName, func(subTest *testing.T) {
			mailmapContent, generateError := GenerateMailmap(testCase.oldIdentity, testCase.newIdentity)
			if testCase.expectError {
				if generateError == nil {
					subTest.Fatal("expected an error but got none")
				}
				return
			}
			if generateError != nil {
				subTest.Fatalf("unexpected error: %v", generateError)
			}
			for _, expectedSubstring := range testCase.expectedSubstrings {
				if !strings.Contains(mailmapContent, expectedSubstring) {
					subTest.Errorf("expected mailmap to contain %q\n---\n%s", expectedSubstring, mailmapContent)
				}
			}
			for _, forbiddenSubstring := range testCase.forbiddenSubstrings {
				if strings.Contains(mailmapContent, forbiddenSubstring) {
					subTest.Errorf("expected mailmap NOT to contain %q", forbiddenSubstring)
				}
			}
		})
	}
}

// TestGenerateMailmapEmptyRepositoryPathGuard is kept here because WriteMailmapFile
// rejects an empty path before any filesystem access, so this branch is pure.
func TestWriteMailmapFileRejectsEmptyPath(testingHandle *testing.T) {
	if writeError := WriteMailmapFile("  ", "content"); writeError == nil {
		testingHandle.Error("expected an error for an empty repository path")
	}
}
