// Package mend generates a .mailmap that remaps how git tools display an old
// identity to the new one. It is the safe, reversible, display-only fix: it
// changes nothing in history, and it neither commits nor pushes.
package mend

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"alive.name/internal/domain"
)

const mailmapFileName = ".mailmap"

const mailmapHeaderComment = "# Generated by alive.name: display-only identity remapping.\n" +
	"# This changes how git tools show names; it does not rewrite history.\n"

// GenerateMailmap builds the text of a .mailmap that maps the old identity to
// the new one. It returns an error if the new identity is incomplete.
//
// Mailmap can only match on a commit email (optionally qualified by a commit
// name); it cannot match on a name alone. So this generates:
//
//   - one entry per old email, remapping any commit with that email; and
//   - one entry per old name paired with the new email, which catches the common
//     case where only the name changed and the email stayed the same; and
//   - one entry per old-name/old-email pair, for explicit combinations.
func GenerateMailmap(oldIdentity domain.OldIdentity, newIdentity domain.NewIdentity) (string, error) {
	trimmedNewName := strings.TrimSpace(newIdentity.Name)
	trimmedNewEmail := strings.TrimSpace(newIdentity.Email)
	if trimmedNewName == "" {
		return "", errors.New("mend: the new name must not be empty")
	}
	if trimmedNewEmail == "" {
		return "", errors.New("mend: the new email must not be empty")
	}

	canonicalPrefix := fmt.Sprintf("%s <%s>", trimmedNewName, trimmedNewEmail)

	uniqueLines := make(map[string]struct{})
	orderedLines := make([]string, 0)
	addLine := func(line string) {
		if _, seen := uniqueLines[line]; seen {
			return
		}
		uniqueLines[line] = struct{}{}
		orderedLines = append(orderedLines, line)
	}

	for _, oldEmail := range oldIdentity.Emails {
		trimmedOldEmail := strings.TrimSpace(oldEmail)
		if trimmedOldEmail == "" {
			continue
		}
		// Form: Proper Name <proper-email> <commit-email>
		addLine(fmt.Sprintf("%s <%s>", canonicalPrefix, trimmedOldEmail))
	}

	for _, oldName := range oldIdentity.Names {
		trimmedOldName := strings.TrimSpace(oldName)
		if trimmedOldName == "" {
			continue
		}
		// Catch the deadname used with the (unchanged) new email.
		// Form: Proper Name <proper-email> Commit Name <commit-email>
		addLine(fmt.Sprintf("%s %s <%s>", canonicalPrefix, trimmedOldName, trimmedNewEmail))
		for _, oldEmail := range oldIdentity.Emails {
			trimmedOldEmail := strings.TrimSpace(oldEmail)
			if trimmedOldEmail == "" {
				continue
			}
			addLine(fmt.Sprintf("%s %s <%s>", canonicalPrefix, trimmedOldName, trimmedOldEmail))
		}
	}

	if len(orderedLines) == 0 {
		return "", errors.New("mend: no old names or emails were supplied to map")
	}

	sort.Strings(orderedLines)

	var builder strings.Builder
	builder.WriteString(mailmapHeaderComment)
	for _, line := range orderedLines {
		builder.WriteString(line)
		builder.WriteString("\n")
	}
	return builder.String(), nil
}

// WriteMailmapFile writes mailmap content to .mailmap at the repository root. It
// does not stage, commit, or push the file; that is always the user's to do.
func WriteMailmapFile(repositoryPath, mailmapContent string) error {
	if strings.TrimSpace(repositoryPath) == "" {
		return errors.New("mend: repository path must not be empty")
	}
	mailmapPath := filepath.Join(repositoryPath, mailmapFileName)
	if writeError := os.WriteFile(mailmapPath, []byte(mailmapContent), 0o644); writeError != nil {
		return fmt.Errorf("mend: writing %s: %w", mailmapPath, writeError)
	}
	return nil
}
